import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";

const roobert = localFont({
  src: [
    {
      path: "./fonts/Roobert/RoobertCollectionVF-TRIAL.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Roobert/RoobertArabicVF-TRIAL.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Roobert/RoobertHebrewCollectionVF-TRIAL.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Roobert/RoobertJapaneseVF-TRIAL.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Roobert/RoobertKoreanVF-TRIAL.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-roobert",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={roobert.variable}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
